repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=100']
    -   id: check-merge-conflict
    -   id: check-yaml
        exclude: meta.yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.26.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: [
            flake8-alfred,
            flake8-bugbear,
            flake8-builtins,
            flake8-comprehensions,
            flake8-docstrings,
            flake8-eradicate,
            flake8-print,
            flake8-pytest-style,
            flake8-todo,
            flake8-unused-arguments,
            pep8-naming,
            pydocstyle,
            Pygments,
        ]
