reward_params:
wage_vocational:
  constant: 1.0
  age: 1.0
  parental_income: 1.0
  ability: 1.0
  uni_dropout: 1.0
  exp: 1.0 
wage_academic:
  constant: 1.0
  age: 1.0 
  parental_income: 1.0 
  ability: 1.0
  exp: 1.0
nonpec_vocational_work:
  constant: 1.0
nonpec_academic_work:
  constant: 1.0
nonpec_havo:
  constant: 1.0
nonpec_mbo4:
  constant: 1.0
nonpec_mbo3:
  constant: 1.0
nonpec_mbo2:
  constant: 1.0
nonpec_hbo:
  constant: 1.0

transition_params:
  hbo_specification:
    min_length: 2
    max_length: 5
  hbo_risk:
    constant: 1.0
    parental_resources: 1.0
    grade_group: 1.0
  hbo_length:
    constant: 1.0
    parental_income: 1.0
    ability: 1.0
  hbo_dropout_length:
    constant: 1.0
    parental_income: 1.0
    ability: 1.0
  havo_specification:
    max_length: 7
    min_length: 3
  havo_risk: 
    constant: 1.0
    parental_income: 1.0
    ability: 1.0
  havo_length:
    constant: 1.0
    parental_income: 1.0
    ability: 1.0
  havo_dropout_length:
    constant: 1.0
  mbo4_specification:
    min_length: 2
    max_length: 6
  mbo4_risk:
    constant: 1.0
    parental_income: 1.0
    ability: 1.0
  mbo4_length:
    constant: 1.0
    parental_income: 1.0
    ability: 1.0
  mbo4_dropout_length:
    constant: 1.0
  mbo3_specification:
    min_length: 2
    max_length: 5
  mbo3_length:
    constant: 1.0
    parental_income: 1.0
    ability: 1.0
  mbo2_specification:
    min_length: 2
    max_length: 5
  mbo2_length:
    constant: 1.0
    parental_income: 1.0
    ability: 1.0
